service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  healthcheckv2: {}
  jaeger_query:
    storage:
      traces: local_badger
  jaeger_storage:
    backends:
      local_badger:
        badger:
          directories:
            keys: "$HOME/STRACE/jaeger-badger/keys"
            values: "$HOME/STRACE/jaeger-badger/values"
          ephemeral: false

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch: {}

exporters:
  jaeger_storage_exporter:
    trace_storage: local_badger